[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pGFNFF_opti"
version = "0.1.0"
dependencies = [
    "ase",
    "numpy",
    "matplotlib",
    "pandas",
    "dscribe",
    "optuna",
    "spglib",
]

[tool.setuptools.packages.find]
where = ["src"]
